sudo: required
services:
  - docker

before_install:
  - docker build -t jayeclissold/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jayeclissold/docker-react npm run test
language: generic
